# Generated by Django 4.1.4 on 2022-12-31 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_remove_blog_image_addimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addimage',
            name='blog',
        ),
    ]
