# Generated by Django 4.1.4 on 2022-12-30 06:32

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authoradditional_readeradditional_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=accounts.models.LowercaseEmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
